// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/proto_message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EchoProtoIn struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoProtoIn) Reset()         { *m = EchoProtoIn{} }
func (m *EchoProtoIn) String() string { return proto.CompactTextString(m) }
func (*EchoProtoIn) ProtoMessage()    {}
func (*EchoProtoIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4a369cfceb21766, []int{0}
}

func (m *EchoProtoIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoProtoIn.Unmarshal(m, b)
}
func (m *EchoProtoIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoProtoIn.Marshal(b, m, deterministic)
}
func (m *EchoProtoIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoProtoIn.Merge(m, src)
}
func (m *EchoProtoIn) XXX_Size() int {
	return xxx_messageInfo_EchoProtoIn.Size(m)
}
func (m *EchoProtoIn) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoProtoIn.DiscardUnknown(m)
}

var xxx_messageInfo_EchoProtoIn proto.InternalMessageInfo

func (m *EchoProtoIn) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type EchoProtoOut struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoProtoOut) Reset()         { *m = EchoProtoOut{} }
func (m *EchoProtoOut) String() string { return proto.CompactTextString(m) }
func (*EchoProtoOut) ProtoMessage()    {}
func (*EchoProtoOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4a369cfceb21766, []int{1}
}

func (m *EchoProtoOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoProtoOut.Unmarshal(m, b)
}
func (m *EchoProtoOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoProtoOut.Marshal(b, m, deterministic)
}
func (m *EchoProtoOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoProtoOut.Merge(m, src)
}
func (m *EchoProtoOut) XXX_Size() int {
	return xxx_messageInfo_EchoProtoOut.Size(m)
}
func (m *EchoProtoOut) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoProtoOut.DiscardUnknown(m)
}

var xxx_messageInfo_EchoProtoOut proto.InternalMessageInfo

func (m *EchoProtoOut) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*EchoProtoIn)(nil), "message.EchoProtoIn")
	proto.RegisterType((*EchoProtoOut)(nil), "message.EchoProtoOut")
}

func init() { proto.RegisterFile("message/proto_message.proto", fileDescriptor_a4a369cfceb21766) }

var fileDescriptor_a4a369cfceb21766 = []byte{
	// 135 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xce, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x8f, 0x87, 0xf2, 0xf4, 0xc0, 0x3c, 0x21,
	0x76, 0x28, 0x57, 0x49, 0x9e, 0x8b, 0xdb, 0x35, 0x39, 0x23, 0x3f, 0x00, 0x24, 0xea, 0x99, 0x27,
	0x24, 0xc0, 0xc5, 0x9c, 0x5b, 0x9c, 0x2e, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x62, 0x2a,
	0x29, 0x70, 0xf1, 0xc0, 0x15, 0xf8, 0x97, 0x96, 0x60, 0xaa, 0x70, 0xd2, 0x8d, 0xd2, 0x4e, 0xcf,
	0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0x4d, 0xcc, 0xcb, 0x48, 0x49, 0xcc,
	0x2f, 0x4b, 0xcc, 0xd3, 0xcf, 0xad, 0x2c, 0x2a, 0x48, 0xd6, 0x4f, 0xad, 0x48, 0xcc, 0x2d, 0xc8,
	0x49, 0xd5, 0x87, 0xda, 0x98, 0xc4, 0x06, 0x76, 0x81, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xab,
	0x69, 0x17, 0xd8, 0xa0, 0x00, 0x00, 0x00,
}
